steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$PROJECT_ID', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$PROJECT_ID']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '$PROJECT_ID', '--image', 'gcr.io/$PROJECT_ID/$PROJECT_ID',
         '--update-secrets=SECRET_KEY=secret-key:latest,DATABASE=database:latest', '--region', 'us-central1']
images:
- gcr.io/$PROJECT_ID/$PROJECT_ID
